name: learn-github-actions
on: pull_request
jobs:
  depScanTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: installing_npm_modules
        run: npm install -g @cyclonedx/cdxgen
      - name: installDepScan
        run: pip install owasp-depscan
      - name: listing
        run: ls -la
      - name: runScan
        run: RESULT=$(depscan --src $PWD -o report) 
      - name: Pull Request Commenter
        uses: Libra-foundation/Pull-Request-Comments@V1.1.1
        with:
          filename: $PWD/report
