name: learn-github-actions
on: pull_request
jobs:
  depScanTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: installing_npm_modules
        run: npm install -g @cyclonedx/cdxgen
      - name: installDepScan
        run: pip install owasp-depscan
      - name: Pull Request Commenter
        uses: int128/comment-action@v1
        with:
          run: depscan --src $PWD
          post-on-success: ${run.output}
